[Feature/BOO-33] 공통 > 드롭다운 메뉴
book-piseo/book-piseo-frontend pull request #28
Opened 2024-05-15 13:38 UTC by im-wen3y

### 작업 사항
- 공통 > 드롭다운 메뉴 컴포넌트 작업

### 이슈 사항
- tailwindCSS 가 안먹히는 현상이 발생함 -> 수정 조치 필요!

2024-05-15 13:45 UTC, im-wen3y commented on src/components/team/TeamBookReviewItem.tsx
> +						</Menu>
Trigger 안에 버튼을 넣고, 하단에 Group 내부에 Item 리스트를 넣으면 됩니다.

2024-05-16 13:13 UTC, im-wen3y commented on src/components/team/TeamBookReviewItem.tsx
> +						</DropdownMenu>
DropdownMenu 로 컴포넌트명을 변경하였습니다. @dev-bomdong

2024-05-16 13:14 UTC, im-wen3y commented on tailwind.config.ts
> +		'./src/ui/**/*.{js,ts,jsx,tsx,mdx}',
이 부분 추가를 안해서 px 로 넣는 arbitrary values가 작동을 안 했던 거였습니다. 또르륵 @dev-bomdong

2024-05-20 14:28 UTC, dev-bomdong commented on src/components/team/TeamBookReviewItem.tsx
> +						</DropdownMenu>
@im-wen3y 혹시 Dropdown => DropdownMenu로 컴포넌트명을 변경하신 이유가 있을까요? 
컴포넌트 파일명이나 디렉토리(ui>dropdown), 관련 컴포넌트들은(DropdownContext등) Dropdown으로 남아있어서 혼선이 있을 수 있을 것 같은데, 둘중 하나로 통일하면 좋을 것 같습니다!

2024-05-20 14:28 UTC, dev-bomdong requested changes
고생하셨습니다 웬디! 궁금한 사항은 코멘트를 남겨두어서, 한번 확인부탁드립니다 :)

2024-05-20 14:30 UTC, dev-bomdong commented on src/ui/dropdown/Dropdown.compound.tsx
> +export default DropdownMenu;
@im-wen3y 코드에 prettier가 적용이 안되어있는 것 같은데, 한 번 확인해주시면 감사하겠습니다!

2024-05-27 11:56 UTC, im-wen3y commented on src/components/team/TeamBookReviewItem.tsx
> +						</DropdownMenu>
`DropdownMenu`라고 대체로 사용하는것 같아서 변경하였는데 폴더명도 변경해두겠습니다!

2024-05-27 12:05 UTC, im-wen3y commented on src/ui/dropdown/Dropdown.compound.tsx
> +export default DropdownMenu;
@dev-bomdong prettier가 적용이 안되는 이슈가 있었는데, 완전하게 껏다 켜니깐 잘 작동하네여! 적용해두었습니다!

2024-05-27 12:07 UTC, im-wen3y commented on src/components/team/TeamBookReviewItem.tsx
> +import DropdownMenu from '@/ui/dropdownMenu/DropdownMenu.compound';
@dev-bomdong pakage.json에 추가하지 않아서 이렇게 노출되는데, (나중에 '따로 ui만 분리한다던가?'를 생각해보니) 나쁘지않은거 같아서 그대로 두었습니다. 추후에 확인하시다가 변경 필요할 거 같다고 생각하시면 적용해두겠습니다!

2024-05-27 12:09 UTC, im-wen3y commented
@dev-bomdong 여행 다녀오신 후, 재확인 부탁드립니다. 문제 없으면 바로 머지하셔서 사용하셔도 될 거 같습니다!

2024-06-10 02:01 UTC, dev-bomdong approved these changes
변경해주신 사항들 확인했습니다! 고생하셨습니다~!

2024-06-10 12:14 UTC, merged